var Message ={
    MS_01 : "Vui lòng nhập !",
    MS_02 : "Phải là số !",
    MS_03 : "Không hợp lệ !",
    MS_04 : "Email không hợp lệ !",
    MS_05 : "Nhập ít nhất 6 kí tự",
    MS_06 : "Mật khẩu không khớp !",
    MS_07 : "Vui lòng chọn !",
    MS_08 : "Vui lòng chọn khoa!",
    MS_09 : "Vui lòng nhập/chọn ngày hẹn !",
    MS_10 : "Vui lòng nhập nguyên nhân triệu chứng !",
    MS_11 : "Nhập tối đa 300 kí tự !",
    MS_12 : "Nhập tối đa 3 kí tự !", 
    MS_13 : "Nhập ít nhất 10 kí tự !",
    MS_14 : "Nhập tối đa 11 kí tự !",
    MS_15 : "Lịch hẹn đang bị trùng với người khác . Vui lòng chọn giờ khác !",
    MS_16 : "Chưa khám cho  bệnh nhân nào !",
    MS_17 : "Không có lịch khám nào !",
    MS_18 : "Không có lịch hẹn với bệnh nhân nào !",
    MS_19 : "Không có lịch khám với bác sĩ nào  !",
    MS_20 : "Không có lịch hẹn nào từ phía bác sĩ !",
    MS_21 : "Không có bệnh án nào !",
    MS_22 : "Vui lòng chọn Khoa và Bác sĩ !",
    MS_23 : "Không có hàng chờ !",
    MS_24 : "Vui lòng chọn xét nghiệm !",
    MS_25 : "Phiếu Xét nghiệm có sẵn , vui lòng kiểm tra lại !",
    MS_26 : "Vui lòng chọn thuốc !",
    MS_27 : "Vui lòng nhập số lượng !",
    MS_28 : "Thuốc đã có sẵn trong toa , vui lòng kiểm tra lại !",
    MS_29 : "Vui lòng nhập đúng dịnh dạng email ! ví dụ: abc@xyz.com !",
    MS_30 : "Nhập tối đa 200 kí tự !",
    MS_31 : "Nhập tối đa 300 kí tự !",
    
};